baseURL = "https://espeople.in/"
languageCode = "en-us"
title = "ESP | Energize, Synergize, People - Unlock Your Business Potential"
theme = 'growth-sketch'
[params]
favicon = "/images/favicon1.ico"
description = "ESP (Energize, Synergize, People) helps businesses unlock their potential through innovative training, leadership development, and team-building solutions. Focused on enhancing organizational growth and performance through proven methods."
keywords = "business training, leadership development, team building, organizational growth, corporate training, ESP, Energize Synergize People, business consulting, performance improvement"
author = "Balachandiran - TenSketch"
logo = "/images/logo.png"
og_image = "/ogimage.jpg"
[asset]
  # Enable Hugo pipes for SCSS
  enable = true

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
    
    [[menu.main]]
      name = "About ESPeople"
      url = "/about/about-espeople"
      parent = "About"
      weight = 1

    [[menu.main]]
      name = "ESP Approach"
      url = "/about/esp-approach"
      parent = "About"
      weight = 1

  [[menu.main]]
    name = "Clientele"
    weight = 3

    [[menu.main]]
      name = "ESP Business"
      url = "/clientele-beneficiaries/esp-business"
      parent = "Clientele"
      weight = 1

    [[menu.main]]
      name = "ESP Non-Profit"
      url = "/clientele-beneficiaries/esp-non-profit"
      parent = "Clientele"
      weight = 3

    [[menu.main]]
      name = "ESP Education"
      url = "/clientele-beneficiaries/esp-education"
      parent = "Clientele"
      weight = 4

    [[menu.main]]
      name = "ESP Government"
      url = "/clientele-beneficiaries/esp-government"
      parent = "Clientele"
      weight = 2

    [[menu.main]]
      name = "ESP Focused individuals"
      url = "/clientele-beneficiaries/esp-focussed-individuals"
      parent = "Clientele"
      weight = 5


  [[menu.main]]
    name = "Other L&D Services"
    url = "/other-Learning-and-Development-services"
    weight = 4
  
  [[menu.main]]
    name = "Downloads"
    url = "/downloads"
    weight = 5    

  [[menu.main]]
    name = "Contact Us"
    url = "/contact-us"
    weight = 6
